App\Domain\Entity\Invoice:
  type: entity
  table: invoices
  schema: db_name
  readOnly: false
  id:
    uuid:
      type: app_invoice_uuid
      generator:
        strategy: NONE
  fields:
    creationDate:
      name: creation_date
      type: datetime_immutable